apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-media-app
  labels:
    app: social-media-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: social-media-app
  template:
    metadata:
      labels:
        app: social-media-app
    spec:
      containers:
      - name: social-media-app
        image: bhandariajay006:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
